### PR TITLE
Fix a soundness hole allowing multiple mutable borrows

### LINKED ISSUE #117: (soundness regression) `static mut` could be avoided.
At least for `inline_lazy`, the `Option<T>` can be wrapped in `Cell`, needing only:
```rust
unsafe impl<T: Sync> Sync for Lazy<T> {}
```
Then we can just have a regular `static` and `get` can take `&'static self` *safely*.

**EDIT**: As noted below (https://github.com/rust-lang-nursery/lazy-static.rs/issues/117#issuecomment-415454944), the use of `&'static mut Lazy<T>` is unsound.
Also, the `impl` above exists already, UB was introduced by regression at https://github.com/rust-lang-nursery/lazy-static.rs/commit/a308da1d1da7660a9577979c64bb30f0ed0700f7.

cc @anp @RalfJung

### PR DESCRIPTION
**Pull request by KodrAus**
Fixes #117 

cc @eddyb @RalfJung

See #117 for more details, we don't need `&'static mut self` receivers on `Lazy` to initialise and get its value. This also has the nice side benefit of making our various `Lazy` impls have a consistent API.

This is a potentially breaking change, @pietroalbini do you think it would be possible to schedule a crater run? Thanks!

### CODE REVIEW

**Comment by KodrAus** [comment]
Ah that's a bit of a nuisance... Looks like `Cell::new` wasn't available in `const fn`s back in `1.21.0`.

**Comment by KodrAus** [comment]
Ok, I've tweaked the `heap_lazy` impl so it doesn't need `&'static mut` or `Cell`. Using `ptr::write` always feels a little... dirty :) So please scrutinize that implementation.

**Comment by eddyb** [comment]
@KodrAus Somewhere else in the codebase a `static mut` is generated, right?
That's a problem.

File: src/heap_lazy.rs [hunk 1]
```diff
@@ -17,18 +18,24 @@ impl<T: Sync> Lazy<T> {
...
-            &*self.0
-        }
+        self.1.call_once(|| {
+            let r = Box::into_raw(Box::new(f()));
+            
+            // This is safe because the `Once` guarantees we
+            // have exclusive access to the value field
+            // The value hasn't been previously initialized
+            unsafe {
+                ptr::write(&self.0 as *const _ as *mut _, r);
```
Comment (eddyb) [inline src/heap_lazy.rs]: You can't turn the `&'static self` into a mutable pointer without `UnsafeCell`.

**Comment by pietroalbini** [comment]
> This is a potentially breaking change, @pietroalbini do you think it would be possible to schedule a crater run? Thanks!

Not at the moment, sorry, the queue is pretty full `:(`

File: src/heap_lazy.rs (hunk 1 above)
Comment (KodrAus) [reply src/heap_lazy.rs]: I thought that might be the case. I'll revert this last commit and bump our minimum version to `1.22` so that we can use `Cell` properly.

We might have to be a bit patient with rolling this one out, the last version bump we did for `1.1.0` was a bit unpopular (to be fair that bumped about 10 versions, instead of 1).

**Comment by KodrAus** [comment]
> Somewhere else in the codebase a static mut is generated, right? That's a problem.

@eddyb Ah well spotted! I totally missed the `static mut` in the macros.

@pietroalbini No problem :) I think we'll hold on to this one for a little while anyways so we don't poison the well with lots of version bumps over a short period.

File: src/inline_lazy.rs [hunk 2]
```diff
@@ -9,27 +9,28 @@ extern crate core;
...
+            self.0.set(Some(f()));
+        });
+
+        // `self.0` is guaranteed to be `Some` by this point
+        // The `Once` will catch and propegate panics
         unsafe {
-            match self.0 {
+            match *self.0.as_ptr() {
                 Some(ref x) => x,
                 None => unreachable_unchecked(),
```
Comment (RalfJung) [inline src/inline_lazy.rs]: Might be worth a `debug_assert!(false)` or so?

Comment (KodrAus) [reply src/inline_lazy.rs]: Good idea :+1: It seems like a fair thing to be more defensive about

**Comment by KodrAus** [comment]
Just noticed that we can close #125 now that we don't use `static mut` anymore so we don't need any external `unsafe` blocks.

**Comment by eddyb** [comment]
@KodrAus Looks great now! Assuming @RalfJung agrees, I think this is good to go.

**Comment by RalfJung** [comment]
There is so much context around these macros, doesn't make it easier to analyze.^^

For `heap_lazy.rs`, the only unsafe bit seems to be to get a shared ref into the leaked `Box`. Seems fine.

`inline_lazy.rs` returns a shared ref into a `Cell`, but that `Cell` will never get mutated again so this also seems fine.

(I think this could be further optimized with `Cell<MaybeInitialized<T>>`, avoiding the `Option` entirely, but that is a separate problem.)

**Comment by KodrAus** [comment]
> I think this could be further optimized with Cell<MaybeInitialized<T>>

Ah good idea. I've added a FIXME for replacing `Option` with some kind of `MaybeInitialized`. That might be a fun thing for someone to contribute along with some benches :)

It sounds like this is ready to merge so I'll go ahead and do that now, but will leave it for a day or two before pushing to crates.io so we can opportunistically bundle #130 too.
