### PR TITLE
WIP Improved support for visibility restrictions

### LINKED ISSUE #87: Does not support `crate` visibility restriction
Consider this example:

```rust
#[macro_use]
extern crate lazy_static;

mod a {
    pub mod b {
        use std::collections::HashMap;
        lazy_static! {
            pub(in a) static ref HASHMAP: HashMap<u32, &'static str> = {
                let mut m = HashMap::new();
                m.insert(0, "baz");
                m
            };
        }
    }
    
    use self::b::HASHMAP;

    pub fn foo() {
        println!("{}", HASHMAP[&0]);
    }
}

fn main() {
    a::foo();
}
```

It works as intended, but if we switch `pub(in a)` to `pub(crate)` (both of which are valid visibility restrictions as of Rust v.1.18 and higher) we get an error:

```
error: no rules expected the token `crate`
 --> src/main.rs:8:17
  |
8 |             pub(crate) static ref HASHMAP: HashMap<u32, &'static str> = {
  |                 ^^^^^
```
I would submit a patch, but unfortunately my macro-foo is not high enough to take on this issue alone (although if someone is willing to mentor I can try to fix this).

### PR DESCRIPTION
**Pull request by fuine**
I marked the PR WIP because I'm not 100% sure one change I introduced is correct.

Closes #87

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -116,24 +116,12 @@ pub use core::ops::Deref as __Deref;
...
+    ($(#[$attr:meta])* ($($vis:tt)*) static ref $N:ident : $T:ty = $e:expr; $($t:tt)*) => {
+        __lazy_static_internal!(@MAKE TY, $(#[$attr])*, ($($vis)*), $N);
         __lazy_static_internal!(@TAIL, $N : $T = $e);
-        __lazy_static_internal!($($t)*);
-    };
-    (@$VIS:ident, $(#[$attr:meta])* static ref $N:ident : $T:ty = $e:expr; $($t:tt)*) => {
-        __lazy_static_internal!(@MAKE TY, $VIS, $(#[$attr])*, $N);
-        __lazy_static_internal!(@TAIL, $N : $T = $e);
-        __lazy_static_internal!($($t)*);
+        lazy_static!($($t)*);
```
Comment (fuine) [inline src/lib.rs]: I'm not sure if this is correct, and why previously call to `__lazy_static_internal!` macro was put in here. This also somewhat duplicated the code. Can someone look at it?

**Comment by fuine** [comment]
Also, is there a way to check for compiler errors in tests? I have added two cases which should result in compilation errors and I have manually confirmed that they do indeed yield those errors, but I'd rather have it automated.

**Comment by fuine** [comment]
It looks like Windows build failed due to the wrong version of stable compiler:

`Downloading rust-1.16.0-i686-pc-windows-gnu.exe (74,903,600 bytes)...100%`

Visibility restrictions have been introduced in `1.18`

**Comment by KodrAus** [comment]
Thanks @fuine! Sorry I don't think I can review this personally.

It looks like there's a `RUST_VERSION` environment variable in AppVeyor that's controlling this. We'll just need to get that bumped up to `1.18`.

For the compile-fail tests, there is the [`compiletest`](https://github.com/laumann/compiletest-rs) crate, but I haven't used it personally and looks like it would mean restructuring the crate's tests somewhat to support. Maybe out-of-scope for this particular change.

@Kimundi what do you think?

**Comment by fuine** [comment]
Thanks, I'm willing to implement tests using `compiletest` if maintainers think this is a good thing to be introduced to the test suite, probably in a separate PR.

**Comment by Kimundi** [comment]
I'd love to have compile tests in this lib! I never got around to adding them myself - would be nice for checking the unused variable warning as well.

If something seems wrong with the appveyor setup feel free to open a PR for fixing it as well - I'm not to familiar with it myself.

**Comment by KodrAus** [comment]
@fuine I've merged in your fix for the AppVeyor build, would you like to rebase this?

**Comment by fuine** [comment]
Sure, but I want to land the `compiletest` support prior to this being merged, I'll open a new PR today/tomorrow

**Comment by KodrAus** [comment]
Sounds good! Thanks @fuine!

**Comment by fuine** [comment]
@KodrAus @Kimundi in the meantime, could you take a look at introduced changes? The only thing that I will change after #90 lands is addition of two compiler tests, but modifications to the crate source files will stay the same.

**Comment by fuine** [comment]
Once tests pass I think that it's good to go, but I still would like someone knowledgable to take a look at the change I commented under in the review - maybe there was some subtlety to the way previous code was designed which I didn't spot and my change breaks some corner cases

File: src/lib.rs (hunk 1 above)
Comment (Kimundi) [reply src/lib.rs]: I'm not aware of a deeper reason for the duplication. As far as I can remember, when the internal macro split from the public one, this just happend with the idea that the publich one acts as the entry point for the internal one, which then just keeps to itself during expansion.

However, there is no reason for why it couldn't do the mutual recursion back into the public one instead, as done in this PR.

The only thing I can imagine is macro 1.0 weirdness in regard to visibility. As in, depending on how its imported, the internal macro might not see the public one during expansion. Not sure if this can happen here though.

Comment (fuine) [reply src/lib.rs]: Thanks for the information. I think that you should decide whether or not you like current implementation better than the previous one. If you do then you can merge the PR, otherwise let me know and I'll revert some changes I made and adapt it so that it plays well with all possible visibility restrictions.

**Comment by Kimundi** [comment]
Alright, looks good! Thanks for the contribution. :)
